== WIS2 Monitoring Event Message Encoding: System Alert Report

System Alert Report payloads published via the WIS2 Monitoring Event Topic (WMET) are defined using the associated requirements and schema described in this Requirements Class.

=== Requirements Class "WIS2 Monitoring Event Message Encoding: System Alert Report"

==== Overview

This Requirements Class provides the requirements for System Alert reports.

include::../requirements/requirements_class_monitoring-event-message-encoding-system-alert.adoc[]

==== Validation

The System Alert report schema is based on the Requirements Class WIS2 Monitoring Event Message Encoding: Core schema and the associated information model, and applies to the ``data`` property of an event report.

include::../requirements/monitoring-event-message-encoding-system-alert/REQ_validation.adoc[]

==== Type

The type of event related to the event message encoding, using a reverse DNS notation.

Example:
[source,json]
----
"type": "int.wmo.wis.wme.event.system.alert"
----

include::../requirements/monitoring-event-message-encoding-system-alert/REQ_type.adoc[]

==== Data schema

The ``dataschema`` property identifies the JSON Schema that is adhered to by event message payload.  This is the value of a given JSON Schema's `$id` property.

Example:
[source,json]
----
"dataschema": "https://schemas.wmo.int/wme/1.0.0/schemas/wis2-event-message-encoding-system-alert.json"
----

include::../requirements/monitoring-event-message-encoding-system-alert/REQ_dataschema.adoc[]

==== Data

TODO
