== Introduction

=== Motivation

WIS2 Global Services provide high availability capabilities in support of discovery, access and exchange of weather/climate/water/environmental data on WIS2.

Once connected to the WIS2 infrastructure, any Global Service will be monitored by the WIS2 Global Monitor.  Monitoring of WIS2 Global Services will allow for detection of service anomalities, interruptions or quality assessments of metadata.  These "events" can jeopardize normal WIS2 Operations.

WIS2 Nodes may plan for data and/or service outages, and may wish to provide a notice to WIS2 Operations for planning and recovery.

A mechanism to notify on and describe such events in support of WIS2 operations and corrective action.  Using the WIS2 Topic Hierarchy and CloudEvents baselines for this specification provide broad interoperability and low barrier publication and event handling for the WIS2 ecosystem and beyond.

=== Scenarios

The following scenarios are useful in understanding the drivers and principles that were used in the
development of this specification:

* _Global Service service down_: a Global Service may cease to operate for any given reason
* _Global Service malfunctioning_: a Global Service may fail to function normally (e.g.: Global Cache not providing messages, etc.)
* _WIS2 Node malfunctioning_:
** a WIS2 Node may publish malformed or invalid WIS2 Notification Messages
** a WIS2 Node may provide correct notifications but no data
* _WIS2 Node data/service outages_:
** a WIS2 Node may be down for maintenance for a given date/time window

These scenarios can be realized as planned/expected outages, or occur suddenly, in an unexpected manner.

Those events should be detected, and the Global Services or WIS2 Nodes should be informed to drive corrective action and succssful operation of WIS2.
