== The WIS2 Monitoring Event Topic

The WIS2 Monitoring Event Topic (WMET) provides a mechanism for Global Services to provide reports and notifications to WIS2 Global Services, as well as data/metadata reports for WIS2 Nodes to subscribe to and receive notifications.

=== Requirements Class "WIS2 Monitoring Event Topic"

==== Overview

This Requirements Class provides requirements for the WIS2 Monitoring Event Topic.

include::../requirements/requirements_class_monitoring-event-topic.adoc[]

Successful operation of the WIS2 infrastructure and monitoring events of same should be information that is made available to all Global Services and WIS2 Nodes, and not designed for communication to external users or data consumers.  Global Services need to be able to report information to Global Services and WIS2 Nodes to trigger corrective action.

The WMET is composed of four levels: A fixed channel of `monitor`, WTH primary topic levels 2 (version), 3 (system), and 4 (centre identifier).  Level 4 is the centre identifier of the subject of the event notification (the _subject_).

The representation is encoded as a simple text string of values in each topic level separated by a slash (``/``). 

Examples:

``monitor/a/wis2/ca-eccc-msc``

``monitor/a/wis2/fr-meteofrance``

The table below provides an overview of the primary topic levels.

.WMET primary topic levels
|===
|Level|Name|Description

|1
|channel
|Location of where the data originates from (fixed value of ``monitor``)

|2
|version
|Alphabetical version of the topic hierarchy

|3
|system
|Fixed value of ``wis2`` for WIS2

|4
|centre-id
|Acronym proposed by Member and endorsed by WMO Secretariat, of the centre identifier of the subject of the event
|===

==== Publishing

A simple ruleset is defined for publishing events to WMET that enables the clear identification of the event subject, to trigger corrective action or as informative notice.

include::../requirements/monitoring-event-topic/REQ_publishing.adoc[]
