== Conventions
This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of JSON Schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this Standard are denoted by the URI:

http://wis.wmo.int/spec/wme/1

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Examples

Monitoring event topics examples provided in this specification are encoded as `plain text strings`.

Monitoring event message examples provided in this specification are encoded as JSON.

Complete examples can be found at https://schemas.wmo.int/wme/1.0/examples

=== Codelists bundle

Given the WIS2 Monitoring Event Topic extends the WIS2 Topic Hierarchy, no additional codelists bundles are made available given the WTH codelists bundles satisfy the requirements of this specification.

=== Schemas

Monitoring event message schemas can be found at https://schemas.wmo.int/wme/1.0

=== Schema representation

JSON Schema footnote:[https://json-schema.org] objects are used throughout this standard to define the structure
of metadata records. These schema objects are also typically represented using YAML footnote:[https://en.wikipedia.org/wiki/YAML].
YAML is a superset of JSON, and in this standard is regarded as equivalent.

Event message instances are always defined as JSON.

==== Properties

A JSON **property** represents a key-value pair, where the key is the name of the property and the value is a standard JSON data type.

[source,json]
----
"myPropertyName": "test123"
----
