== WIS2 Monitoring Event Message Encoding: Notice

Notice payloads published via the WIS2 Monitoring Event Topic (WMET) are defined using the associated requirements and schema described in this Requirements Class.

=== Requirements Class "WIS2 Monitoring Event Message Encoding: Notice"

==== Overview

This Requirements Class provides the requirements for Notices.  Notices can be used for administrative messages about general operational and/or administrative matters or for service messages about operational status and/or problem resolution matters. Notices are used to provide information relating to interruptions of or changes to stable WIS2 operations.

include::../requirements/requirements_class_monitoring-event-message-encoding-notice.adoc[]

Examples of Notices include (but are not limited to):

- a WIS2 Node is planning a significant service outage period
- a WIS2 Node is experienceing an unplanned service outage or contingency situation

==== Validation

The Notice report schema is based on the Requirements Class WIS2 Monitoring Event Message Encoding: Core schema and the associated information model, and applies to the ``data`` property of an event report.

include::../requirements/monitoring-event-message-encoding-notice/REQ_validation.adoc[]

==== Type

The type of event related to the event message encoding, using a reverse DNS notation.

Example:
[source,json]
----
"type": "int.wmo.wis.wme.event.notice"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_type.adoc[]

==== Data schema

The ``dataschema`` property identifies the JSON Schema that is adhered to by event message payload.  This is the value of a given JSON Schema's `$id` property.

Example:
[source,json]
----
"dataschema": "https://schemas.wmo.int/wme/1.0.0/schemas/wis2-event-message-encoding-notice.json"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_dataschema.adoc[]

==== Data

The Notice report ``data`` property provides the event payload in JSON, using the "Problem Details" schema of <<ogcapi-common-part1,OGC API - Common - Part 1: Core>> as the content model.

==== Data ``type``

The ``data.type`` property defines a URN that is prefixed by ``wmem-alert`` and based on <<wis2-metric-hierarchy,WIS2 Metric Hierarchy>> alert names footnote:[https://github.com/wmo-im/wis2-metric-hierarchy/tree/main/alerts].

Example:
[source,json]
----
"type": "wmem-alert:Planned_service_outage_at_node"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_data_type.adoc[]

==== Data ``title``

The ``data.title`` property defines a texual summary based on <<wis2-metric-hierarchy,WIS2 Metric Hierarchy>> alert summary annotations footnote:[https://github.com/wmo-im/wis2-metric-hierarchy/tree/main/alerts].

Example:
[source,json]
----
"title": "Planned service outage at node"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_data_title.adoc[]

==== Data ``detail``

The ``data.detail`` property defines a detailed description of the problem, as defined by the issuer of the Notice.

Example:
[source,json]
----
"detail": "Planned outage of all data from METEOSAT-12 for 36 hours from 20250722T093000Z due to spacecraft decontamination"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_data_detail.adoc[]

==== Data ``wmem:severity``

The ``data.wmem:severity`` property defines a list of severity levels to describe the seriousness of an event.

Example:
[source,json]
----
"wmem:severity": "critical"
----

include::../requirements/monitoring-event-message-encoding-notice/REQ_data_wmem-severity.adoc[]