== WIS2 Monitoring Event Message Encoding

Event payloads published via the WIS2 Monitoring Event Topic (WET) are defined using the <<cloud-events,CloudEvents>> specification as a building block.

=== Requirements Class "WIS2 Monitoring Event Message Encoding: Core"

==== Overview

This Requirements Class provides baseline requirements for all WIS2 event and report types.

CloudEvents provides a standards-based encoding for all event data, and provides mechanisms for extensibility.

include::../requirements/requirements_class_monitoring-event-message-encoding-core.adoc[]

The table below provides an overview of the set of properties that are included in a WIS2 Monitoring Event Message (WEM).

.WEM core properties
|===
|Property|Requirement|Description

|``id``
|**Required**
|A universally unique identifier (UUID) of the message (see <<_identifier>>)

|``specversion``
|**Required**
|The CloudEvents specification version (see <<_version>>)

|``source``
|**Required**
|The centre identifier producing the event (see <<_source>>)

|``type``
|**Required**
|The event type related to the message (see <<_type>>)

|``subject``
|**Required**
|The centre identifier of the intended target of the event (see <<_subject>>)

|``time``
|**Required**
|The date and time of when the notification was published, in RFC3339 format, UTC (see <<_time>>)

|``datacontenttype``
|**Required**
|The media type of the data content encoding in the event message (`application/json`) (see <<_data_content_type>>)

|``dataschema``
|**Required**
|The JSON schema which is adhered to by the data content encoding in the event message (see <<_data_schema>>)

|``data``
|**Required**
|The event payload as JSON (see <<_data>>)
|===

==== Message size

The WIS2 Monitoring Event Message Encoding allows for the transmission of event messages in a compact manner.

include::../requirements/monitoring-event-message-encoding-core/REQ_message_size.adoc[]

==== Identifier

A universally unique identifier of the event using the UUID standard (link:https://datatracker.ietf.org/doc/html/rfc4122[RFC4122]). The identifier is generated by the originator of the event.

Example:
[source,json]
----
"id": "6e1c7f9f-dd6c-48d9-bbc4-aef0625f1fb8"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_id.adoc[]

==== Version

The CloudEvents specification version of the event message encoding.

Example:
[source,json]
----
"specversion": "1.0"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_version.adoc[]

==== Source

The centre identifier of the event producer (as defined in the <<wis2-topic-hierarchy>>).

Example:
[source,json]
----
"source": "ca-eccc-msc-global-discovery-catalogue"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_source.adoc[]

==== Type

The type of event related to the event message encoding, using a reverse DNS notation.

Example:
[source,json]
----
"type": "int.wmo.wis.wme.event.wcmp2"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_type.adoc[]

==== Subject

The centre identifier of the intended target of the event (as defined in the <<wis2-topic-hierarchy>>).

Example:
[source,json]
----
"subject": "de-dwd"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_subject.adoc[]

==== Time

The ``time`` property identifies the date/time when the notification was first posted or published by the originator. The date/time is encoded in RFC3339 format with the Coordinated Universal Time (UTC) timezone (``Z``).

Example:
[source,json]
----
"time": "2024-10-17T03:42:23Z"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_time.adoc[]

==== Data content type

The ``datacontenttype`` property identifies the media type associated with the event message payload.  `application/json` (JSON) is the required media type for all data specific encodings.

Example:
[source,json]
----
"datacontenttype": "application/json"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_datacontenttype.adoc[]

==== Data schema

The ``dataschema`` property identifies the JSON Schema that is adhered to by event message payload.  This is the value of a given JSON Schema's `$id` property.

Example:
[source,json]
----
"dataschema": "https://schemas.wmo.int/wcmp/2.0.0/schemas/wcmp2-bundled.json"
----

include::../requirements/monitoring-event-message-encoding-core/REQ_dataschema.adoc[]

==== Data

The ``data`` property provides the event payload in JSON.

Example:
[source,json]
----
"data": {
    "id": "ab7cd199-ffa3-4909-80be-c78e99791435",
    "report_type": "ets",
    "summary": {
        "PASSED": 12,
        "FAILED": 0,
        "SKIPPED": 0
    },
    "generated_by": "pywcmp 0.10.1 (https://github.com/wmo-im/pywcmp)",
    "tests": [
        {
            "id": "http://wis.wmo.int/spec/wcmp/2/conf/core/conformance",
            "code": "PASSED",
            "message": "Passes given schema is compliant/valid"
        },
        ...
    }
}
----

include::../requirements/monitoring-event-message-encoding-core/REQ_data.adoc[]
