== WIS2 Monitoring Event Message

Event messages published via the WIS2 Monitoring Event Topic (WMET) are defined using the <<cloud-events,CloudEvents>> specification as a building block.

Examples of event messages, include, but are not limited to:

* a WIS2 Global Discovery Catalogue’s metadata archive being older than 24 hours
* a WIS2 Node being disconnected from all Global Brokers
* a WIS2 Node not providing any data in the last 6 hours
* a WIS2 Node providing a notice on service interruptions during a given date/time window

=== Requirements Class "WIS2 Monitoring Event Message: Core"

==== Overview

This Requirements Class provides baseline requirements for all WIS2 event message types.

CloudEvents provides a standards-based encoding for all event data, and provides mechanisms for extensibility.

include::../requirements/requirements_class_monitoring-event-message-core.adoc[]

The table below provides an overview of the set of properties that are included in a WIS2 Monitoring Event Message (WMEM).

.WMEM core properties
|===
|Property|Requirement|Description

|``id``
|**Required**
|A universally unique identifier (UUID) of the message (see <<_identifier>>)

|``specversion``
|**Required**
|The CloudEvents specification version (see <<_version>>)

|``type``
|**Required**
|The event type related to the message (see <<_type>>)

|``source``
|**Required**
|The centre identifier of the event message originator or producer (see <<_source>>)

|``subject``
|**Required**
|The centre identifier of the subject of the event (see <<_subject>>)

|``time``
|**Required**
|The date and time of when the notification was published, in RFC3339 format, UTC (see <<_time>>)

|``datacontenttype``
|**Required**
|The media type of the data content encoding in the event message (`application/json`) (see <<_data_content_type>>)

|``dataschema``
|**Required**
|The JSON Schema that is adhered to by the event message (see <<_data_schema>>)

|``data``
|**Required**
|The event payload as JSON (see <<_data>>)

|``data.conformsTo``
|**Required**
|The version of WME associated to which the event message conforms (see <<_data_conformance>>)

|``data.severity``
|**Required**
|The severity level of the event (see <<_data_severity>>)

|``data.ref``
|Optional
|The identifier that the event is referencing (see <<_data_ref>>)

|``data.channel``
|Optional
|The WIS2 channel related to the event (see <<_data_channel>>)

|``data.time``
|Optional
|The date/time associated with the event (see <<_data_time>>)

|``data.content``
|**Required** (any of `+data.content+` and/or `+data.links+`)
|Inline content describing the event, including a human readable title of the event (see <<_data_content>>)

|``data.links``
|**Required** (any of `+data.content+` and/or `+data.links+`)
|Online linkages for message retrieval or additional resources associated with the event (see <<_data_links>>)

|===

==== Validation

The WIS2 Monitoring Event Message schema is based on the Requirements Class WIS2 Monitoring Event Message: Core schema and the associated information model.

include::../requirements/monitoring-event-message-core/REQ_validation.adoc[]

==== Message size

The WIS2 Monitoring Event Message allows for the transmission of event messages in a compact manner.

include::../requirements/monitoring-event-message-core/REQ_message_size.adoc[]

==== Identifier

A universally unique identifier of the event using the UUID standard (link:https://datatracker.ietf.org/doc/html/rfc9562[RFC9562]). The identifier is generated by the originator of the event.

Example:
[source,json]
----
"id": "6e1c7f9f-dd6c-48d9-bbc4-aef0625f1fb8"
----

include::../requirements/monitoring-event-message-core/REQ_id.adoc[]
include::../recommendations/monitoring-event-message-core/REC_id.adoc[]

==== Version

The CloudEvents specification version of the event message.

Example:
[source,json]
----
"specversion": "1.0"
----

include::../requirements/monitoring-event-message-core/REQ_version.adoc[]

==== Type

The type of event related to the event message, using a reverse DNS notation.

Example:
[source,json]
----
"type": "int.wmo.wis.wme.event"
----

include::../requirements/monitoring-event-message-core/REQ_type.adoc[]

==== Source

The centre identifier of the event message originator or producer (as defined in the <<wis2-topic-hierarchy>>).

Example:
[source,json]
----
"source": "ca-eccc-msc-global-discovery-catalogue"
----

include::../requirements/monitoring-event-message-core/REQ_source.adoc[]

==== Subject

The centre identifier associated with the description of the event (as defined in the <<wis2-topic-hierarchy>>).

Example:
[source,json]
----
"subject": "de-dwd"
----

include::../requirements/monitoring-event-message-core/REQ_subject.adoc[]

==== Time

The ``time`` property identifies the date/time when the notification was first posted or published by the originator. The date/time is encoded in RFC3339 format with the Coordinated Universal Time (UTC) timezone (``Z``).

Example:
[source,json]
----
"time": "2024-10-17T03:42:23Z"
----

include::../requirements/monitoring-event-message-core/REQ_time.adoc[]

==== Data content type

The ``datacontenttype`` property identifies the media type associated with the event message payload.  `application/json` (JSON) is the required media type for all data specific encodings.

Example:
[source,json]
----
"datacontenttype": "application/json"
----

include::../requirements/monitoring-event-message-core/REQ_datacontenttype.adoc[]

==== Data schema

The ``dataschema`` property identifies the JSON Schema that is adhered to by event message payload.  This is the value of a given JSON Schema's `$id` property.

Example:
[source,json]
----
"dataschema": "https://schemas.wmo.int/wme/1.0.0/schemas/wis2-event-message-bundled.json"
----

include::../requirements/monitoring-event-message-core/REQ_dataschema.adoc[]

==== Data

The ``data`` property provides the event payload in JSON.

Example:
[source,json]
----
"data": {
    "conformsTo": [
        "http://wis.wmo.int/spec/wme/1/conf/monitoring-event-message-core"
    ],
    "severity": "INFO",
    "content": {
        "id": "ab7cd199-ffa3-4909-80be-c78e99791435",
        "title": "WCMP2 ETS report",
        "report_type": "ets",
        "summary": {
            "PASSED": 12,
            "FAILED": 0,
            "SKIPPED": 0
        },
        "generated_by": "pywcmp 0.13.1 (https://github.com/wmo-im/pywcmp)",
        "tests": [
            {
                "id": "http://wis.wmo.int/spec/wcmp/2/conf/core/conformance",
                "code": "PASSED",
                "message": "Passes given schema is compliant/valid"
            },
            ...
        }
    }
}
----

include::../requirements/monitoring-event-message-core/REQ_data.adoc[]
include::../recommendations/monitoring-event-message-core/PER_data.adoc[]

==== Data conformance

The ``conformsTo`` property identifies the version of the WME standard to which the event message conforms. Conformance identification is valuable for version detection and handling of content.

[source,json]
----
"conformsTo": [
    "http://wis.wmo.int/spec/wme/1/conf/monitoring-event-message-core"
]
----

include::../requirements/monitoring-event-message-core/REQ_data_conformance.adoc[]

==== Data severity

The ``data.severity`` property defines a list of severity levels to describe the seriousness of an event.

Example:
[source,json]
----
"severity": "CRITICAL"
----

include::../requirements/monitoring-event-message-core/REQ_data_severity.adoc[]

==== Data ref

The ``data.ref`` property defines an identifier that the event is referencing (for example, to refer/follow up on a previous monitoring event).

Example:
[source,json]
----
"ref": "6da24af0-b19f-4106-b583-73cc25a4435d"
----

==== Data channel

The ``data.channel`` property defines a WIS2 topic that the event may be referring to (for example for a data outage notice).

Example:
[source,json]
----
"channel": "origin/a/wis2/ar-smn/data/core/weather/surface-based-observations/synop"
----

include::../recommendations/monitoring-event-message-core/REC_data_channel.adoc[]

==== Data time

The ``data.time`` property defines time interval that the WMEM may be referring to (for example for a data outage notice).

Examples:

[source,json]
----
"time": {
  "interval": [
      "2025-09-18T12:00:00Z",
      "2025-09-18T16:00:00Z"
  ]
}
----

[source,json]
----
"time": {
  "interval": [
      "2025-09-18T12:00:00Z",
      ".."
  ]
}
----

[source,json]
----
"time": {
  "interval": [
      "..",
      "2025-09-18T16:00:00Z"
  ]
}
----

include::../recommendations/monitoring-event-message-core/REC_data_time.adoc[]
include::../recommendations/monitoring-event-message-core/PER_data_time.adoc[]

==== Data content

The ``data.content`` property provides an inline description and summary of the event.

Example:
[source,json]
----
"content": {
    "id": "ab7cd199-ffa3-4909-80be-c78e99791435",
    "title": "WCMP2 ETS report",
    "report_type": "ets",
    "summary": {
        "PASSED": 12,
        "FAILED": 0,
        "SKIPPED": 0
    },
    "generated_by": "pywcmp 0.13.1 (https://github.com/wmo-im/pywcmp)",
    "tests": [
        {
            "id": "http://wis.wmo.int/spec/wcmp/2/conf/core/conformance",
            "code": "PASSED",
            "message": "Passes given schema is compliant/valid"
        },
        ...
    }
}
----

include::../requirements/monitoring-event-message-core/REQ_data_content.adoc[]
include::../recommendations/monitoring-event-message-core/PER_data_content.adoc[]

===== Data content title

The ``data.content.title`` property defines a texual summary of the <<wis2-metric-hierarchy,WIS2 Metric Hierarchy>> alert summary annotations footnote:[https://github.com/wmo-im/wis2-metric-hierarchy/tree/main/alerts].

Example:
[source,json]
----
"title": "Metadata archive is older than 24 hours"
----

include::../requirements/monitoring-event-message-core/REQ_data_content_title.adoc[]

===== Data content description

The ``data.content.description`` property defines a detailed description of the problem, as defined by the issuer of the event.

Example:
[source,json]
----
"description": "Metadata archive is older than 24 hours.  Please contact the administrator at admin@example.org for more information"
----

include::../recommendations/monitoring-event-message-core/REC_data_content_description.adoc[]

==== Data links

The ``data.links`` array property consists of one or more objects providing URLs to access data.

Each link object provides:

* An ``href`` property with a fully qualified link to access the data;
* A ``rel`` property providing an link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relation] or link:http://codes.wmo.int/wis/link-type[WIS link type] describing the relationship between the link and the message;
* A ``type`` property providing the media type of the data;
* A ``length`` property providing the length (in bytes) indicating the size of the data;
* A ``security`` property providing a description of the access control mechanism applied (for example, recommended data with restrictions).
 
Links can be used when including inline messages via `data.content` is not required, desired, or feasible.

.Example: Canonical link
[source,json]
----
"links": [{
  "href": "https://example.org/global-cache-2025-12-21-13.log.gz",
  "rel": "canonical",
  "type": "application/gzip"
}]
----

.Example: Multiple links
[source,json]
----
"links": [{
  "href": "https://example.org/global-cache-2025-12-21-13.log.gz",
  "rel": "canonical",
  "type": "application/gzip"
}, {
  "href": "https://example.org/global-cache-log-dashboard/2025-12-21-13",
  "rel": "alternate",
  "type": "text/html"
}]
----

include::../requirements/monitoring-event-message-core/REQ_data_links.adoc[]
include::../recommendations/monitoring-event-message-core/REC_data_links.adoc[]
include::../recommendations/monitoring-event-message-core/PER_data_links.adoc[]

===== Access control

WMEM links may also provide links to resources that implement access control in support of authentication and authorization. The example demonstrates how to express access control using HTTP Basic authentication for a given Global Cache logging dashboard.

.Example: Access controlled link
[source,json]
----
"links": [{
  "href": "https://example.org/global-cache-log-dashboard/2025-12-21-13",
  "rel": "alternate",
  "type": "text/html",
  "title": "link to Global Cache logging dashboard",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the service provider for accessing this secured resource."
    }
  }
}]
----
